version: "3.5"
services:
  mev-boost:
    build:
      context: src
      args:
        UPSTREAM_VERSION: v1.7-alpha1
    volumes:
      - "data:/var/lib/mev-boost"
    environment:
      RELAYS: ""
      EXTRA_OPTS: ""
    restart: unless-stopped
volumes:
  data: {}
